version: "3.8"
services: 
  db:
    image: postgres:14.2
    container_name: database_ecommerce
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-ecomerce:/var/lib/postgresql/data
volumes:
  db-ecomerce: